### ISSUE TITLE
Getting error while running the dataset code

### ISSUE THREAD

**Issue by Raj800** [ai-tor/VPilot#21]
C:\Anaconda3\python.exe "D:/Utilities/Raj/Project/GTA mods/VPilot-master/dataset"
Trying to connect to DeepGTAV
ERROR: Failed to connect to DeepGTAV
Traceback (most recent call last):
ERROR: Failed to send message. Reason: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
  File "D:/Utilities/Raj/Project/GTA mods/VPilot-master/dataset", line 35, in <module>
    message = client.recvMessage()  
  File "D:\Utilities\Raj\Project\GTA mods\VPilot-master\deepgtav\client.py", line 52, in recvMessage
    frame = self._recvall()
  File "D:\Utilities\Raj\Project\GTA mods\VPilot-master\deepgtav\client.py", line 66, in _recvall
    packet = self.s.recv(4 - len(data))
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied

**Comment by Raj800** [comment]
Solved the error with few changes in socket exception handling.
